// GRE 500 essential words, clustered into meaning-families for recall.
// Each cluster: { id, section, title, gloss, hook, words:[{w, d, anti?}] }
// `anti:true` marks a word that sits at the OPPOSITE pole of the cluster's main meaning.

export const SECTIONS = [
  "Conflict & Harmony",
  "Truth & Trust",
  "Speech & Expression",
  "Temperament & Mood",
  "Character & Conduct",
  "Quantity & Spread",
  "Change, Time & Permanence",
  "Thinking & Judgment",
  "Power, Support & Action",
  "Order, Norms & Structure",
  "Loners",
];

export const CLUSTERS = [
  // ---------------- Conflict & Harmony ----------------
  {
    id: "soothe",
    section: "Conflict & Harmony",
    title: "Turn the heat down — or up",
    gloss: "Easing pain, anger, or intensity — and the opposites that stoke it.",
    hook: "Picture a nurse who ABATES the fever and MOLLIFIES the cranky patient — versus an arsonist who FOMENTS panic and EXACERBATES the chaos. One pole turns the dial down; the other cranks it up.",
    words: [
      { w: "abate", d: "reduce, diminish" },
      { w: "alleviate", d: "lessen, make easier to bear" },
      { w: "assuage", d: "soothe, relieve" },
      { w: "mitigate", d: "make less severe" },
      { w: "mollify", d: "calm an angry person" },
      { w: "placate", d: "pacify, win over" },
      { w: "appease", d: "satisfy to keep the peace" },
      { w: "conciliatory", d: "peacemaking, reconciling" },
      { w: "console", d: "comfort in grief" },
      { w: "subside", d: "settle down, die away" },
      { w: "exacerbate", d: "make worse", anti: true },
      { w: "foment", d: "stir up, incite", anti: true },
      { w: "incendiary", d: "inflaming, provocative", anti: true },
      { w: "antagonize", d: "make hostile", anti: true },
    ],
  },
  {
    id: "praise",
    section: "Conflict & Harmony",
    title: "Pedestal vs. pillory",
    gloss: "Lifting someone up with praise — or tearing them down.",
    hook: "KUDOS and a EULOGY put you on a pedestal; CASTIGATE and VITUPERATE nail you to the pillory. ADMONISH is just a finger-wag along the way.",
    words: [
      { w: "laudable", d: "praiseworthy" },
      { w: "estimable", d: "worthy of admiration" },
      { w: "eulogy", d: "speech of high praise" },
      { w: "kudos", d: "praise, credit, glory" },
      { w: "venerate", d: "revere deeply" },
      { w: "reverent", d: "showing deep respect" },
      { w: "anoint", d: "consecrate; mark as chosen" },
      { w: "admonish", d: "mildly scold, caution", anti: true },
      { w: "castigate", d: "criticize or punish severely", anti: true },
      { w: "censure", d: "formal stern reprimand", anti: true },
      { w: "denigrate", d: "belittle, attack the reputation of", anti: true },
      { w: "deride", d: "mock, ridicule", anti: true },
      { w: "vituperate", d: "verbally abuse", anti: true },
      { w: "debase", d: "degrade, lower in value", anti: true },
      { w: "discredit", d: "injure the reputation of", anti: true },
    ],
  },
  {
    id: "harshwords",
    section: "Conflict & Harmony",
    title: "Words that draw blood",
    gloss: "A cutting tone — and the loud, harsh noise it makes.",
    hook: "CAUSTIC acid burns skin; CAUSTIC, ABRASIVE, SCATHING words burn pride. Let them run on and you get a DIATRIBE or TIRADE; let a crowd join and it is pure CACOPHONY.",
    words: [
      { w: "caustic", d: "corrosive; bitingly sarcastic" },
      { w: "abrasive", d: "harsh, irritating" },
      { w: "scathing", d: "savagely critical" },
      { w: "diatribe", d: "bitter, abusive rant" },
      { w: "tirade", d: "long angry speech" },
      { w: "clamor", d: "noisy outcry, uproar" },
      { w: "defamatory", d: "slanderous, reputation-harming" },
      { w: "cacophony", d: "harsh, discordant mix of sounds" },
      { w: "din", d: "loud, confused, lasting noise" },
      { w: "dissonance", d: "harsh, clashing sound; disagreement" },
    ],
  },
  {
    id: "fight",
    section: "Conflict & Harmony",
    title: "Spoiling for a fight",
    gloss: "People and issues that pick fights.",
    hook: "PUGNACIOUS = ready to PUNCH. A CONTENTIOUS issue makes everyone QUIBBLE, DISSENT, and GAINSAY until the room is POLARIZED.",
    words: [
      { w: "pugnacious", d: "eager to fight, combative" },
      { w: "contentious", d: "controversial; argumentative" },
      { w: "quibble", d: "argue over trivial points" },
      { w: "dissent", d: "disagree, esp. formally" },
      { w: "gainsay", d: "deny, contradict, oppose" },
      { w: "polarized", d: "split into hostile camps" },
      { w: "anarchy", d: "absence of order; chaos" },
    ],
  },

  // ---------------- Truth & Trust ----------------
  {
    id: "honest",
    section: "Truth & Trust",
    title: "The real thing vs. the put-on",
    gloss: "Genuine, transparent character — and the phonies who fake it.",
    hook: "ARTLESS and INGENUOUS people have nothing to hide; the DISINGENUOUS, MENDACIOUS, and GLIB are all performing. SPECIOUS and APOCRYPHAL = looks true, isn't.",
    words: [
      { w: "candid", d: "open, frank, honest" },
      { w: "ingenuous", d: "innocently frank; naive" },
      { w: "artless", d: "without guile, natural" },
      { w: "probity", d: "integrity, uprightness" },
      { w: "veracity", d: "truthfulness, accuracy" },
      { w: "fidelity", d: "faithfulness, loyalty" },
      { w: "principled", d: "guided by strong morals" },
      { w: "disingenuous", d: "insincere, falsely naive", anti: true },
      { w: "affectation", d: "put-on, fake behavior", anti: true },
      { w: "phony", d: "fake, counterfeit", anti: true },
      { w: "bogus", d: "fraudulent, not genuine", anti: true },
      { w: "specious", d: "false but plausible-looking", anti: true },
      { w: "apocryphal", d: "of doubtful authenticity", anti: true },
      { w: "mendacious", d: "habitually lying", anti: true },
      { w: "glib", d: "fluent but insincere", anti: true },
    ],
  },
  {
    id: "sly",
    section: "Truth & Trust",
    title: "The fox's toolkit",
    gloss: "Cleverness bent toward deceit.",
    hook: "GUILE, WILY, CRAFTY — all the fox's tricks. COVERT keeps them hidden; PERFIDIOUS betrays the trust it earned; a face that BELIES the truth lies to you.",
    words: [
      { w: "crafty", d: "cunning, scheming" },
      { w: "guile", d: "sly deceit, cunning" },
      { w: "wily", d: "full of tricks" },
      { w: "covert", d: "secret, concealed" },
      { w: "perfidious", d: "treacherous, disloyal" },
      { w: "belie", d: "misrepresent; give a false impression" },
    ],
  },
  {
    id: "doubt",
    section: "Truth & Trust",
    title: "I don't buy it",
    gloss: "Healthy doubt — and the opposite, believing too easily.",
    hook: "A SKEPTIC is DUBIOUS and WARY; a CYNIC assumes the worst. The CREDULOUS, by contrast, swallow anything — the opposite trap.",
    words: [
      { w: "skeptic", d: "one who doubts / questions" },
      { w: "cynical", d: "distrustful of motives; pessimistic" },
      { w: "dubious", d: "doubtful, questionable" },
      { w: "wary", d: "cautious, on guard" },
      { w: "credulous", d: "too ready to believe; gullible", anti: true },
    ],
  },
  {
    id: "expose",
    section: "Truth & Trust",
    title: "Pulling back the curtain",
    gloss: "Proving something false, or dragging it into the light.",
    hook: "DEBUNK and REFUTE knock a claim down; DISABUSE frees you of a wrong belief; UNEARTH digs up what was buried; EXCULPATE clears the wrongly accused.",
    words: [
      { w: "debunk", d: "expose as false or exaggerated" },
      { w: "refute", d: "prove wrong" },
      { w: "negate", d: "nullify, deny" },
      { w: "repudiate", d: "reject, disown" },
      { w: "rescind", d: "cancel, repeal" },
      { w: "disabuse", d: "free from a mistaken belief" },
      { w: "unearth", d: "dig up, uncover" },
      { w: "exculpate", d: "clear of guilt or blame" },
    ],
  },

  // ---------------- Speech & Expression ----------------
  {
    id: "talk",
    section: "Speech & Expression",
    title: "Motormouth vs. clam",
    gloss: "Those who never stop talking — and those who barely start.",
    hook: "GARRULOUS, LOQUACIOUS, VERBOSE = the motormouths. LACONIC, TACITURN, RETICENT = the clams who keep it short.",
    words: [
      { w: "garrulous", d: "rambling, talkative" },
      { w: "loquacious", d: "very talkative" },
      { w: "verbose", d: "wordy, long-winded" },
      { w: "laconic", d: "using very few words", anti: true },
      { w: "taciturn", d: "habitually silent, reserved", anti: true },
      { w: "reticent", d: "reluctant to speak", anti: true },
    ],
  },
  {
    id: "persuade",
    section: "Speech & Expression",
    title: "The art of the pitch",
    gloss: "Speaking well enough to move people.",
    hook: "An ELOQUENT, ARTICULATE speaker makes a COGENT case. RHETORIC is the craft, HYPERBOLE the exaggeration, DIDACTIC the lecture, and to AVER is to state it with full confidence.",
    words: [
      { w: "eloquent", d: "fluent, moving in speech" },
      { w: "articulate", d: "expressing oneself clearly" },
      { w: "cogent", d: "convincing, logical" },
      { w: "rhetoric", d: "the art of persuasion" },
      { w: "hyperbole", d: "deliberate exaggeration" },
      { w: "embellish", d: "decorate; exaggerate a story with extra detail" },
      { w: "didactic", d: "meant to instruct or moralize" },
      { w: "aver", d: "declare confidently as true" },
    ],
  },
  {
    id: "clear",
    section: "Speech & Expression",
    title: "Crystal clear vs. clear as mud",
    gloss: "Easy to grasp — or deliberately hard.",
    hook: "LUCID, EXPLICIT, UNEQUIVOCAL leave no doubt. AMBIGUOUS, OPAQUE, CONVOLUTED, ARCANE keep you guessing; DISJOINTED just falls apart.",
    words: [
      { w: "lucid", d: "clear, easy to follow" },
      { w: "explicit", d: "stated plainly and fully" },
      { w: "intelligible", d: "able to be understood" },
      { w: "unequivocal", d: "absolutely clear" },
      { w: "patent", d: "obvious, plain to see" },
      { w: "pronounced", d: "distinct, strongly marked" },
      { w: "ambiguous", d: "open to several readings", anti: true },
      { w: "opaque", d: "unclear, hard to see through", anti: true },
      { w: "convoluted", d: "twisted, overly complex", anti: true },
      { w: "arcane", d: "obscure, known to few", anti: true },
      { w: "esoteric", d: "understood by a select few", anti: true },
      { w: "disjointed", d: "disconnected, incoherent", anti: true },
    ],
  },
  {
    id: "essence",
    section: "Speech & Expression",
    title: "Getting to the point",
    gloss: "The essence of a thing — and what is meant but left unsaid.",
    hook: "DISTILL down to the GIST and the PITH — the core. TACIT and IMPLICIT meanings are felt, not spoken; FIGURATIVE language is never literal; UNDERSCORE the part that matters.",
    words: [
      { w: "gist", d: "main point, essence" },
      { w: "pith", d: "core, essential part" },
      { w: "distill", d: "extract the essence of" },
      { w: "nuance", d: "subtle shade of meaning" },
      { w: "finesse", d: "delicacy, subtle skill" },
      { w: "figurative", d: "metaphorical, not literal" },
      { w: "virtual", d: "existing in essence / in effect" },
      { w: "construe", d: "interpret, make sense of" },
      { w: "denote", d: "indicate, stand for literally" },
      { w: "implication", d: "something implied" },
      { w: "implicit", d: "implied, not stated" },
      { w: "tacit", d: "understood without being said" },
      { w: "underscore", d: "emphasize" },
    ],
  },
  {
    id: "riddle",
    section: "Speech & Expression",
    title: "Beats me",
    gloss: "Puzzles, contradictions, and things that don't add up.",
    hook: "An ENIGMA, CONUNDRUM, or PARADOX leaves you stumped; an ANOMALY just doesn't fit the pattern; something COUNTERINTUITIVE defies what you'd expect.",
    words: [
      { w: "enigma", d: "puzzle, mystery" },
      { w: "conundrum", d: "riddle; hard problem" },
      { w: "paradox", d: "self-contradiction that may be true" },
      { w: "anomaly", d: "deviation from the norm" },
      { w: "quandary", d: "state of perplexity, dilemma" },
      { w: "counterintuitive", d: "against what you'd expect" },
    ],
  },
  {
    id: "topic",
    section: "Speech & Expression",
    title: "On topic, off topic, in detail",
    gloss: "Sticking to the point — or drifting from it — and how fully you cover it.",
    hook: "GERMANE stays on point; DIGRESS, go TANGENTIAL, and you've wandered; EXTRANEOUS stuff doesn't belong at all. ENUMERATE and DELINEATE cover it in full.",
    words: [
      { w: "germane", d: "relevant and fitting" },
      { w: "tangential", d: "only loosely relevant" },
      { w: "extraneous", d: "irrelevant, foreign to the matter" },
      { w: "digress", d: "wander off the topic" },
      { w: "jargon", d: "insider vocabulary of a group" },
      { w: "abridge", d: "condense, shorten" },
      { w: "enumerate", d: "list one by one" },
      { w: "delineate", d: "describe in detail; outline" },
      { w: "contextualize", d: "set within its background" },
      { w: "exhaustive", d: "thorough, complete" },
    ],
  },

  // ---------------- Temperament & Mood ----------------
  {
    id: "bold",
    section: "Temperament & Mood",
    title: "Nerves of steel vs. cold feet",
    gloss: "Courage and resolve — and their collapse.",
    hook: "INTREPID, AUDACIOUS, HARDY charge in with RESOLUTION; CRAVEN and TIMOROUS get cold feet, BALK, and are easily DAUNTed.",
    words: [
      { w: "audacious", d: "boldly daring" },
      { w: "intrepid", d: "fearless" },
      { w: "hardy", d: "bold and robust" },
      { w: "presumptuous", d: "overbold, taking liberties" },
      { w: "resolution", d: "firm determination" },
      { w: "craven", d: "utterly cowardly", anti: true },
      { w: "timorous", d: "timid, fearful", anti: true },
      { w: "daunt", d: "intimidate, discourage", anti: true },
      { w: "balk", d: "refuse to go on", anti: true },
    ],
  },
  {
    id: "calm",
    section: "Temperament & Mood",
    title: "Steady vs. all over the place",
    gloss: "Unshakable temperaments — and the changeable, jittery ones.",
    hook: "PLACID, STOIC, STOLID don't flinch. MERCURIAL, VOLATILE, CAPRICIOUS swing with the wind — mercury the metal never sits still — while the PRECARIOUS and DISQUIETING keep everyone on edge.",
    words: [
      { w: "placid", d: "calm, peaceful" },
      { w: "stoic", d: "indifferent to pain or pleasure" },
      { w: "stolid", d: "unemotional, impassive" },
      { w: "sanguine", d: "cheerfully optimistic" },
      { w: "mercurial", d: "quick to change mood", anti: true },
      { w: "volatile", d: "unstable, explosive", anti: true },
      { w: "capricious", d: "impulsive, whimsical", anti: true },
      { w: "erratic", d: "inconsistent, wandering", anti: true },
      { w: "whimsical", d: "guided by passing whims", anti: true },
      { w: "fanciful", d: "whimsical, imaginative", anti: true },
      { w: "restive", d: "restless, fidgety", anti: true },
      { w: "precarious", d: "unstable, insecure, risky", anti: true },
      { w: "disquieting", d: "disturbing, unsettling", anti: true },
    ],
  },
  {
    id: "impartial",
    section: "Temperament & Mood",
    title: "On the fence vs. taking sides",
    gloss: "Judging without a stake — versus prejudice.",
    hook: "A DISINTERESTED judge is IMPARTIAL and DISPASSIONATE (and EQUITABLE, EGALITARIAN). A PARTISAN is PARTIAL, PREDISPOSED, ARBITRARY. Note: disinterested = unbiased, NOT bored.",
    words: [
      { w: "impartial", d: "unbiased, fair" },
      { w: "disinterested", d: "having no stake; neutral" },
      { w: "detached", d: "aloof, uninvolved" },
      { w: "objective", d: "fact-based, neutral" },
      { w: "equitable", d: "fair, even-handed" },
      { w: "dispassionate", d: "calm and unbiased" },
      { w: "egalitarian", d: "believing in equality for all" },
      { w: "partial", d: "biased toward one side", anti: true },
      { w: "partisan", d: "blindly loyal to a side", anti: true },
      { w: "chauvinism", d: "blind group/national loyalty", anti: true },
      { w: "illiberality", d: "narrow-mindedness, bigotry", anti: true },
      { w: "predisposed", d: "inclined beforehand", anti: true },
      { w: "subjective", d: "based on personal feeling", anti: true },
      { w: "arbitrary", d: "based on whim, not reason", anti: true },
    ],
  },
  {
    id: "merry",
    section: "Temperament & Mood",
    title: "Life of the party",
    gloss: "Warm, cheerful, fun-loving.",
    hook: "AFFABLE and GREGARIOUS love a crowd; JOCULAR, SPORTIVE, FACETIOUS love a joke; LEVITY keeps it light and ELATED is the high.",
    words: [
      { w: "affable", d: "warm, friendly, easy-going" },
      { w: "gregarious", d: "sociable, flock-loving" },
      { w: "jocular", d: "joking, playful" },
      { w: "sportive", d: "playful, frolicsome" },
      { w: "facetious", d: "joking, esp. when one shouldn't" },
      { w: "levity", d: "lightness of mood" },
      { w: "elated", d: "joyful, in high spirits" },
      { w: "cosmopolitan", d: "worldly, at home anywhere" },
    ],
  },
  {
    id: "eager",
    section: "Temperament & Mood",
    title: "All in",
    gloss: "Enthusiasm — sometimes more than is wanted.",
    hook: "ALACRITY = cheerful speed; AVID and ZEALOUS are all in; FANATICAL, OFFICIOUS, and PATHOLOGICAL take it too far. Handle each task with DISPATCH.",
    words: [
      { w: "alacrity", d: "cheerful, prompt willingness" },
      { w: "avid", d: "keenly enthusiastic" },
      { w: "zeal", d: "passionate fervor" },
      { w: "fanatical", d: "excessively devoted" },
      { w: "solicitous", d: "eagerly attentive; anxious" },
      { w: "officious", d: "meddlesome, pushily helpful" },
      { w: "pathological", d: "compulsive; caused by disease" },
      { w: "dispatch", d: "promptness; to send off speedily" },
    ],
  },
  {
    id: "apathy",
    section: "Temperament & Mood",
    title: "Running on empty",
    gloss: "Not caring — and no energy to.",
    hook: "APATHY and INDIFFERENCE don't care; TORPOR, LASSITUDE, LANGUID describe the body too tired to. SOPORIFIC puts you under; DORMANT is fully asleep.",
    words: [
      { w: "apathy", d: "lack of feeling or interest" },
      { w: "indifferent", d: "uninterested, unmoved" },
      { w: "torpor", d: "sluggishness, lethargy" },
      { w: "lassitude", d: "weariness, listlessness" },
      { w: "languid", d: "drooping, slow, weak" },
      { w: "soporific", d: "sleep-inducing" },
      { w: "enervate", d: "drain of energy, weaken" },
      { w: "flag", d: "tire, lose vigor" },
      { w: "dormant", d: "inactive, asleep" },
    ],
  },
  {
    id: "dislike",
    section: "Temperament & Mood",
    title: "Keeping away",
    gloss: "Aversion — and the urge to retreat from people.",
    hook: "ANTIPATHY and ABHOR = deep dislike; ESCHEW means avoid; a RECLUSE withdraws entirely; a PARIAH is cast out by everyone else.",
    words: [
      { w: "antipathy", d: "deep dislike, aversion" },
      { w: "abhor", d: "detest, loathe" },
      { w: "eschew", d: "deliberately avoid, shun" },
      { w: "recluse", d: "one who lives in seclusion" },
      { w: "pariah", d: "social outcast" },
      { w: "alienate", d: "make hostile or distant" },
    ],
  },
  {
    id: "leanings",
    section: "Temperament & Mood",
    title: "Which way you lean",
    gloss: "A person's natural bent or mood.",
    hook: "Your DISPOSITION is your default weather; a PENCHANT is the pull toward a favorite thing.",
    words: [
      { w: "disposition", d: "natural mood or tendency" },
      { w: "penchant", d: "strong liking or inclination" },
    ],
  },

  // ---------------- Character & Conduct ----------------
  {
    id: "spare",
    section: "Character & Conduct",
    title: "Monk vs. spendthrift",
    gloss: "Going without on purpose — versus reckless excess.",
    hook: "An ASCETIC lives AUSTERE and SPARTAN, practicing TEMPERANCE in STARK bare rooms; a PRODIGAL is PROFLIGATE and LAVISH, blowing through a SURFEIT of everything.",
    words: [
      { w: "ascetic", d: "severely self-denying" },
      { w: "austere", d: "stern; without luxury" },
      { w: "spartan", d: "disciplined, frugal, plain" },
      { w: "temperance", d: "moderation, self-restraint" },
      { w: "frugal", d: "thrifty, sparing" },
      { w: "abstain", d: "refrain, hold back" },
      { w: "stark", d: "bare, harsh, utter" },
      { w: "prodigal", d: "recklessly wasteful", anti: true },
      { w: "profligate", d: "shamelessly extravagant / immoral", anti: true },
      { w: "lavish", d: "extravagantly abundant", anti: true },
      { w: "surfeit", d: "excess, overindulgence", anti: true },
    ],
  },
  {
    id: "humble",
    section: "Character & Conduct",
    title: "Humble pie vs. hot air",
    gloss: "Down-to-earth — or full of itself.",
    hook: "MODEST and PRAGMATIC keep it grounded; PRETENTIOUS and COMPLACENT puff up; to AGGRANDIZE is to inflate; PATRONIZING talks down to you.",
    words: [
      { w: "modest", d: "humble, unassuming" },
      { w: "pristine", d: "pure, unspoiled, original" },
      { w: "pragmatic", d: "practical, down-to-earth" },
      { w: "pretentious", d: "claiming undue importance", anti: true },
      { w: "complacent", d: "smug, self-satisfied", anti: true },
      { w: "aggrandize", d: "exaggerate, inflate", anti: true },
      { w: "patronizing", d: "condescending", anti: true },
    ],
  },
  {
    id: "servile",
    section: "Character & Conduct",
    title: "Yes-man",
    gloss: "Groveling to win favor or out of duty.",
    hook: "A SYCOPHANT is OBSEQUIOUS — fawning and flattering; to SUPPLICATE is to beg; DEFERENCE bows to authority.",
    words: [
      { w: "obsequious", d: "fawning, servile" },
      { w: "sycophant", d: "flatterer, toady" },
      { w: "supplicate", d: "beg humbly" },
      { w: "deference", d: "respectful submission" },
    ],
  },
  {
    id: "pliable",
    section: "Character & Conduct",
    title: "Putty vs. mule",
    gloss: "Bends to influence — or refuses to budge.",
    hook: "MALLEABLE metal, PLASTIC clay, a TRACTABLE, COMPLIANT horse — all easily shaped or led. The OBSTINATE, INTRACTABLE mule won't move an inch.",
    words: [
      { w: "malleable", d: "easily shaped or influenced" },
      { w: "plastic", d: "able to be molded" },
      { w: "tractable", d: "easily managed or led" },
      { w: "compliant", d: "obedient, yielding" },
      { w: "obstinate", d: "stubborn, set in place", anti: true },
      { w: "intractable", d: "hard to control or manage", anti: true },
    ],
  },
  {
    id: "manners",
    section: "Character & Conduct",
    title: "Minding your manners",
    gloss: "Good taste and decorum — versus the lout.",
    hook: "DECOROUS conduct shows PROPRIETY and respects the MORES; a BOOR is GAUCHE, GAWKY, and UNSEEMLY at the table.",
    words: [
      { w: "decorous", d: "proper, in good taste" },
      { w: "propriety", d: "correctness of behavior" },
      { w: "mores", d: "a group's customs and morals" },
      { w: "boor", d: "rude, ill-mannered person", anti: true },
      { w: "gauche", d: "socially awkward, tactless", anti: true },
      { w: "gawky", d: "physically awkward, ungainly", anti: true },
      { w: "unseemly", d: "improper, indecent", anti: true },
    ],
  },
  {
    id: "lowroad",
    section: "Character & Conduct",
    title: "The low road",
    gloss: "Moral baseness, pleasure-chasing, and small sins.",
    hook: "BASE character sinks low; a LIBERTINE and HEDONIST chase pleasure; a PECCADILLO is just a small slip; NOTORIETY is fame earned the wrong way.",
    words: [
      { w: "base", d: "morally low, dishonorable" },
      { w: "libertine", d: "morally unrestrained person" },
      { w: "hedonist", d: "pleasure-seeker" },
      { w: "peccadillo", d: "minor sin or fault" },
      { w: "notoriety", d: "fame for bad reasons" },
    ],
  },

  // ---------------- Quantity & Spread ----------------
  {
    id: "plenty",
    section: "Quantity & Spread",
    title: "Overflowing vs. running dry",
    gloss: "More than enough — and not nearly enough.",
    hook: "COPIOUS, PROFUSE, REPLETE = brimming; a SPATE or SLEW is a sudden flood; PAUCITY and SCANT are the dry well, and STINGY won't share a drop.",
    words: [
      { w: "copious", d: "plentiful, abundant" },
      { w: "profuse", d: "pouring out abundantly" },
      { w: "replete", d: "filled, well-stocked" },
      { w: "prodigious", d: "enormous, impressive" },
      { w: "rife", d: "widespread, abundant" },
      { w: "spate", d: "sudden outpouring, flood" },
      { w: "slew", d: "a large number" },
      { w: "appreciable", d: "large enough to notice" },
      { w: "satiate", d: "fill or satisfy fully" },
      { w: "saturate", d: "soak or fill thoroughly" },
      { w: "paucity", d: "scarcity, too little", anti: true },
      { w: "scant", d: "barely enough", anti: true },
      { w: "stingy", d: "ungenerous with money", anti: true },
    ],
  },
  {
    id: "spread",
    section: "Quantity & Spread",
    title: "Catching on",
    gloss: "Growing and spreading until it is everywhere.",
    hook: "BURGEON and PROLIFERATE grow fast; DISSEMINATE and PERMEATE spread it around until it is PERVASIVE and UBIQUITOUS — everywhere at once.",
    words: [
      { w: "burgeon", d: "grow or flourish rapidly" },
      { w: "proliferate", d: "multiply rapidly" },
      { w: "disseminate", d: "scatter widely, broadcast" },
      { w: "disperse", d: "scatter, spread out" },
      { w: "permeate", d: "spread through every part" },
      { w: "pervasive", d: "spreading throughout" },
      { w: "ubiquitous", d: "present everywhere at once" },
      { w: "augment", d: "make larger, add to" },
      { w: "enhance", d: "increase in value or quality" },
      { w: "elevate", d: "raise up, lift" },
    ],
  },
  {
    id: "peak",
    section: "Quantity & Spread",
    title: "Topping out",
    gloss: "Reaching the summit, or surpassing the rest.",
    hook: "ACME, ZENITH, CRESCENDO all peak; CULMINATE is the grand finish; OUTSTRIP, ECLIPSE, and OVERSHADOW leave everyone else behind.",
    words: [
      { w: "acme", d: "highest point, summit" },
      { w: "zenith", d: "peak, culmination" },
      { w: "crescendo", d: "rising to a climax" },
      { w: "culminate", d: "reach the high point / final stage" },
      { w: "outstrip", d: "surpass, exceed" },
      { w: "eclipse", d: "outshine, obscure" },
      { w: "overshadow", d: "dominate, outshine" },
      { w: "eminent", d: "distinguished, lofty" },
    ],
  },
  {
    id: "wreck",
    section: "Quantity & Spread",
    title: "Down it goes",
    gloss: "Shrinking, drying up, falling, and spoiling.",
    hook: "PLUMMET straight down; IMPLODE inward; DESICCATE to dust; CONSTRICT to a squeeze; DEFACE to ruin. Everything here gets smaller or worse.",
    words: [
      { w: "plummet", d: "fall sharply, plunge" },
      { w: "implode", d: "collapse violently inward" },
      { w: "desiccate", d: "dry up completely" },
      { w: "constrict", d: "squeeze, narrow, restrict" },
      { w: "deface", d: "vandalize, mar the surface of" },
    ],
  },

  // ---------------- Change, Time & Permanence ----------------
  {
    id: "fleeting",
    section: "Change, Time & Permanence",
    title: "Here and gone vs. here to stay",
    gloss: "Lasting a moment — or built in for good.",
    hook: "EPHEMERAL, FLEETING, TRANSITORY vanish fast; INGRAINED, INHERENT, INTRINSIC are baked in for keeps; STATIC just never moves.",
    words: [
      { w: "ephemeral", d: "short-lived, fleeting" },
      { w: "fleeting", d: "passing quickly" },
      { w: "transitory", d: "temporary, brief" },
      { w: "sporadic", d: "occasional, irregular" },
      { w: "static", d: "fixed, unchanging", anti: true },
      { w: "ingrained", d: "deeply fixed, rooted", anti: true },
      { w: "inherent", d: "built-in, essential", anti: true },
      { w: "intrinsic", d: "belonging to the core nature", anti: true },
    ],
  },
  {
    id: "begin",
    section: "Change, Time & Permanence",
    title: "First light",
    gloss: "Just starting out, or coming before.",
    hook: "NASCENT, INCIPIENT, INCHOATE are barely begun; a PRECURSOR comes first and FORESHADOWs what's next; a PREAMBLE or PROLOGUE opens the show; what's IMMINENT is about to land.",
    words: [
      { w: "nascent", d: "just coming into being" },
      { w: "incipient", d: "in an early stage" },
      { w: "inchoate", d: "undeveloped, just started" },
      { w: "novel", d: "new, fresh, original" },
      { w: "precursor", d: "forerunner, what comes before" },
      { w: "preamble", d: "opening statement, preface" },
      { w: "prologue", d: "opening section of a work" },
      { w: "foreshadow", d: "hint at beforehand" },
      { w: "imminent", d: "about to happen" },
      { w: "prospective", d: "potential, expected, future" },
    ],
  },
  {
    id: "old",
    section: "Change, Time & Permanence",
    title: "Days gone by",
    gloss: "From an earlier time, or out of date.",
    hook: "ARCHAIC and OBSOLETE belong to BYGONE days; a RETROSPECTIVE and a POSTHUMOUS tribute look back; VINTAGE and RUSTIC wear their age well.",
    words: [
      { w: "archaic", d: "old-fashioned, ancient" },
      { w: "obsolete", d: "out of date, no longer used" },
      { w: "bygone", d: "past, former" },
      { w: "vintage", d: "fine and from an earlier time" },
      { w: "posthumous", d: "occurring after death" },
      { w: "retrospective", d: "looking back at the past" },
      { w: "rustic", d: "of the simple countryside" },
    ],
  },
  {
    id: "waver",
    section: "Change, Time & Permanence",
    title: "Can't make up your mind",
    gloss: "Swinging back and forth, unable to settle.",
    hook: "VACILLATE and OSCILLATE swing to and fro; an AMBIVALENT mind is stuck in an INDETERMINATE, QUALIFIED maybe.",
    words: [
      { w: "vacillate", d: "waver between choices" },
      { w: "oscillate", d: "swing back and forth" },
      { w: "ambivalent", d: "having mixed feelings" },
      { w: "indeterminate", d: "not settled, vague" },
      { w: "qualified", d: "limited, conditional, hedged" },
    ],
  },
  {
    id: "time",
    section: "Change, Time & Permanence",
    title: "On the clock",
    gloss: "When things happen and in what order.",
    hook: "SIMULTANEOUS and SYNCHRONOUS = at once; CHRONOLOGICAL = in order; a JUNCTURE or LANDMARK is the critical moment; TIMELY is right on cue.",
    words: [
      { w: "chronological", d: "in time order" },
      { w: "simultaneous", d: "at the same time" },
      { w: "synchronous", d: "occurring together in time" },
      { w: "succeeding", d: "coming after, following" },
      { w: "juncture", d: "critical point in time" },
      { w: "landmark", d: "a milestone; defining moment" },
      { w: "timely", d: "well-timed, opportune" },
      { w: "respectively", d: "in the order already given" },
    ],
  },

  // ---------------- Thinking & Judgment ----------------
  {
    id: "wise",
    section: "Thinking & Judgment",
    title: "Quick on the uptake",
    gloss: "Good judgment and a keen, learned mind.",
    hook: "SAGACIOUS, JUDICIOUS, PRUDENT all show wisdom; DISCERNING and KEEN catch what others miss; ERUDITE is deeply read; PROFOUND goes deep.",
    words: [
      { w: "sagacious", d: "wise, shrewd" },
      { w: "judicious", d: "showing good judgment" },
      { w: "prudent", d: "wise and cautious" },
      { w: "discerning", d: "perceptive, insightful" },
      { w: "discriminating", d: "having refined judgment / taste" },
      { w: "erudite", d: "deeply learned, scholarly" },
      { w: "keen", d: "sharp, perceptive" },
      { w: "profound", d: "deep, insightful" },
      { w: "connoisseur", d: "expert of refined taste" },
    ],
  },
  {
    id: "dull",
    section: "Thinking & Judgment",
    title: "Nothing to see here",
    gloss: "Boring, common, unremarkable.",
    hook: "MUNDANE, PROSAIC, PEDESTRIAN, QUOTIDIAN — every flavor of dull; HACKNEYED is the worn-out cliche; MONOTONY is the drone; PONDEROUS is heavy going.",
    words: [
      { w: "mundane", d: "ordinary, everyday" },
      { w: "prosaic", d: "dull, unimaginative" },
      { w: "pedestrian", d: "commonplace, uninspired" },
      { w: "quotidian", d: "daily, ordinary" },
      { w: "hackneyed", d: "overused, stale" },
      { w: "monotony", d: "tedious sameness" },
      { w: "ponderous", d: "heavy, dull, labored" },
      { w: "lackluster", d: "dull, lacking shine" },
      { w: "trifling", d: "trivial, of little worth" },
    ],
  },
  {
    id: "odd",
    section: "Thinking & Judgment",
    title: "Marching to its own beat",
    gloss: "Out of the ordinary, breaking the pattern.",
    hook: "ABERRANT and INCONGRUOUS break the pattern; a MAVERICK and an ECCENTRIC choose to; an IDIOSYNCRASY is your own quirk; a DISCREPANCY is where two things fail to match.",
    words: [
      { w: "aberrant", d: "deviating from the norm" },
      { w: "eccentric", d: "quirky, unconventional" },
      { w: "incongruous", d: "out of place, mismatched" },
      { w: "maverick", d: "independent nonconformist" },
      { w: "idiosyncrasy", d: "personal quirk or habit" },
      { w: "discrepancy", d: "difference, inconsistency" },
      { w: "autonomous", d: "self-governing, independent" },
    ],
  },
  {
    id: "proof",
    section: "Thinking & Judgment",
    title: "Show your work",
    gloss: "Backing a claim with hard evidence.",
    hook: "EMPIRICAL data CORROBORATEs and SUBSTANTIATEs your case; DOCUMENT it, ASCERTAIN the facts, and your CREDIBILITY holds.",
    words: [
      { w: "empirical", d: "based on observation / experiment" },
      { w: "corroborate", d: "confirm with evidence" },
      { w: "substantiate", d: "back up with proof" },
      { w: "document", d: "support with evidence" },
      { w: "ascertain", d: "find out for certain" },
      { w: "credibility", d: "believability, trustworthiness" },
      { w: "efficacy", d: "power to produce an effect" },
    ],
  },
  {
    id: "guess",
    section: "Thinking & Judgment",
    title: "Reading the tea leaves",
    gloss: "Reasoning toward what isn't yet known.",
    hook: "SURMISE and SPECULATE are guesses; EXTRAPOLATE projects from data; DIVINE and FATHOM reach for hidden truth; SOUND the depths before you DEEM it so.",
    words: [
      { w: "surmise", d: "guess, infer" },
      { w: "speculate", d: "form a theory; guess" },
      { w: "extrapolate", d: "extend a trend to predict" },
      { w: "divine", d: "intuit; discover by insight" },
      { w: "fathom", d: "understand deeply; measure depth" },
      { w: "sound", d: "measure the depth of; probe" },
      { w: "presumptive", d: "based on assumption / inference" },
      { w: "deem", d: "judge, consider to be" },
    ],
  },
  {
    id: "sound",
    section: "Thinking & Judgment",
    title: "Holds up vs. falls apart",
    gloss: "Reasoning you can trust — and reasoning you can't.",
    hook: "PLAUSIBLE, FEASIBLE, VIABLE plans hold up and are WARRANTED; TENUOUS, FALLACIOUS, ERRONEOUS ones are FUTILE — they fall apart at a push.",
    words: [
      { w: "plausible", d: "believable, reasonable" },
      { w: "feasible", d: "doable, likely to work" },
      { w: "viable", d: "workable, able to succeed" },
      { w: "warranted", d: "justified, called for" },
      { w: "tenuous", d: "flimsy, having little substance", anti: true },
      { w: "fallacious", d: "based on a logical error", anti: true },
      { w: "erroneous", d: "mistaken, wrong", anti: true },
      { w: "futile", d: "producing no useful result", anti: true },
    ],
  },

  // ---------------- Power, Support & Action ----------------
  {
    id: "strengthen",
    section: "Power, Support & Action",
    title: "Shore it up vs. tear it down",
    gloss: "Reinforcing — and quietly undermining.",
    hook: "BOLSTER, BUTTRESS, FORTIFY, CONSOLIDATE add support; UNDERMINE, IMPAIR, IMPEDE sap and block it from below.",
    words: [
      { w: "bolster", d: "prop up, support" },
      { w: "buttress", d: "reinforce, support" },
      { w: "fortify", d: "strengthen, invigorate" },
      { w: "consolidate", d: "combine and strengthen" },
      { w: "undermine", d: "weaken from below", anti: true },
      { w: "impair", d: "damage, weaken", anti: true },
      { w: "impede", d: "obstruct, hold back", anti: true },
      { w: "deflect", d: "turn aside, fend off", anti: true },
    ],
  },
  {
    id: "lead",
    section: "Power, Support & Action",
    title: "Out in front",
    gloss: "Leading a cause and making things happen.",
    hook: "An ADVOCATE and EXPONENT speak for a cause; a CATALYST and SPEARHEAD make it move; ACTIVISM and PHILANTHROPY put it to work.",
    words: [
      { w: "advocate", d: "argue in favor of; a supporter" },
      { w: "exponent", d: "a promoter or champion" },
      { w: "catalyst", d: "agent that causes change" },
      { w: "spearhead", d: "lead the charge" },
      { w: "activism", d: "vigorous campaigning for a goal" },
      { w: "philanthropy", d: "charitable giving / goodwill" },
    ],
  },
  {
    id: "giveup",
    section: "Power, Support & Action",
    title: "Letting it go",
    gloss: "Surrendering or handing over a claim, right, or thing.",
    hook: "ABDICATE a throne, ABJURE a belief, DIVEST your shares, CONCEDE the point. To RENDER or CONFER is to hand it over; REQUITE is to give back in return.",
    words: [
      { w: "abdicate", d: "formally give up power" },
      { w: "abjure", d: "renounce, esp. under oath" },
      { w: "divest", d: "strip of; sell off holdings" },
      { w: "concede", d: "give in, admit, yield" },
      { w: "relegate", d: "demote, send to a lower place" },
      { w: "render", d: "give, submit, hand over" },
      { w: "confer", d: "grant, bestow; also consult" },
      { w: "requite", d: "repay, reciprocate, return" },
      { w: "default", d: "fail to act or to pay" },
    ],
  },
  {
    id: "forbid",
    section: "Power, Support & Action",
    title: "Not on my watch",
    gloss: "Stopping, banning, or replacing something.",
    hook: "A DETERRENT discourages; PROHIBITIVE rules block; PROSCRIBE bans outright; OBVIATE and PREEMPT head it off first; SUPERSEDE shoves the old aside.",
    words: [
      { w: "deterrent", d: "something that discourages" },
      { w: "prohibitive", d: "tending to forbid / prevent" },
      { w: "proscribe", d: "prohibit, outlaw, denounce" },
      { w: "obviate", d: "make unnecessary, prevent" },
      { w: "preempt", d: "forestall; take the place of" },
      { w: "supersede", d: "replace, take over from" },
      { w: "dismiss", d: "send away; reject; fire" },
    ],
  },
  {
    id: "harm",
    section: "Power, Support & Action",
    title: "Toxic vs. totally fine",
    gloss: "Does damage — or does none.",
    hook: "DELETERIOUS and ADVERSE do harm; ONEROUS weighs you down; EGREGIOUS is glaringly bad. BENIGN, INNOCUOUS, SALUBRIOUS are safe — even healthy.",
    words: [
      { w: "deleterious", d: "harmful, unhealthful" },
      { w: "adverse", d: "unfavorable, harmful, opposing" },
      { w: "onerous", d: "burdensome, oppressive" },
      { w: "egregious", d: "conspicuously bad, flagrant" },
      { w: "benign", d: "harmless; kindly", anti: true },
      { w: "innocuous", d: "harmless, inoffensive", anti: true },
      { w: "salubrious", d: "healthful, wholesome", anti: true },
    ],
  },
  {
    id: "help",
    section: "Power, Support & Action",
    title: "Smoothing the way",
    gloss: "Making things easier, safer, or drawing them out.",
    hook: "FACILITATE the process, an INCENTIVE motivates, a BUFFER cushions, a HAVEN shelters, REMEDIAL classes fix it. ELICIT draws it out; INFORM gives it life.",
    words: [
      { w: "facilitate", d: "make easier, help along" },
      { w: "incentive", d: "a motivating reward" },
      { w: "buffer", d: "cushion, shield, absorb shock" },
      { w: "haven", d: "refuge, safe place" },
      { w: "remedial", d: "corrective, curative" },
      { w: "elicit", d: "call forth, draw out, evoke" },
      { w: "inform", d: "inspire, animate, give substance to" },
    ],
  },

  // ---------------- Order, Norms & Structure ----------------
  {
    id: "norms",
    section: "Order, Norms & Structure",
    title: "By the book",
    gloss: "Established beliefs and the orthodox line — versus the reformer.",
    hook: "DOGMA and the ORTHODOX, CANONICAL line is 'by the book'; the STATUS QUO is how things stand; ADHERE to it or, like the LIBERAL reformer, push past it. SACROSANCT things can't be touched.",
    words: [
      { w: "dogma", d: "authoritative set of doctrines" },
      { w: "orthodox", d: "conventional, traditional" },
      { w: "canonical", d: "authorized, accepted as standard" },
      { w: "status quo", d: "the existing state of affairs" },
      { w: "sacrosanct", d: "sacred, not to be touched" },
      { w: "pious", d: "devoutly religious" },
      { w: "secular", d: "non-religious, worldly" },
      { w: "adhere", d: "stick to (a plan or belief)" },
      { w: "liberal", d: "favoring reform / generous", anti: true },
    ],
  },
  {
    id: "rank",
    section: "Order, Norms & Structure",
    title: "Where it falls",
    gloss: "Tiers, ranges, and stepwise order.",
    hook: "A HIERARCHY ranks top to bottom; a SPECTRUM and GRADATION span a range; STANDING is your rung; a POTENTATE sits at the top of the BUREAUCRACY.",
    words: [
      { w: "hierarchy", d: "ranked order of importance" },
      { w: "spectrum", d: "full range, broad band" },
      { w: "gradation", d: "gradual step-by-step progression" },
      { w: "standing", d: "rank, status, reputation" },
      { w: "ranks", d: "the personnel; a body of people" },
      { w: "potentate", d: "a powerful ruler" },
      { w: "entitlement", d: "a claimed right" },
      { w: "bureaucracy", d: "rule by many petty officials / red tape" },
    ],
  },
  {
    id: "join",
    section: "Order, Norms & Structure",
    title: "Coming together",
    gloss: "Merging into one — or pulling apart.",
    hook: "COALESCE, CONVERGE, AGGREGATE all come together; INCORPORATE absorbs; CONCUR agrees and CLINCHes it. The opposite is to DIVERGE and split off.",
    words: [
      { w: "coalesce", d: "merge, fuse, unite" },
      { w: "converge", d: "come together toward a point" },
      { w: "aggregate", d: "gather into a whole" },
      { w: "incorporate", d: "blend in, include, combine" },
      { w: "concur", d: "agree" },
      { w: "clinch", d: "settle conclusively" },
      { w: "reap", d: "gather in, harvest" },
      { w: "hodgepodge", d: "jumbled mixture" },
      { w: "eclectic", d: "drawn from many varied sources" },
      { w: "counterpoint", d: "a contrasting element set against another" },
      { w: "diverge", d: "branch apart, differ", anti: true },
    ],
  },
  {
    id: "match",
    section: "Order, Norms & Structure",
    title: "Models & matches",
    gloss: "Patterns to copy, and things that correspond.",
    hook: "EMULATE the PARADIGM; ANALOGOUS and COMMENSURATE things line up; COMPLEMENTARY pieces complete each other; DERIVATIVE just copies without spark.",
    words: [
      { w: "emulate", d: "imitate in order to equal or surpass" },
      { w: "paradigm", d: "model, pattern, framework" },
      { w: "analogous", d: "comparable, parallel" },
      { w: "commensurate", d: "proportionate, equivalent" },
      { w: "complementary", d: "completing each other" },
      { w: "homogeneous", d: "all of the same kind, uniform" },
      { w: "derivative", d: "unoriginal, copied from elsewhere" },
    ],
  },
  {
    id: "edge",
    section: "Order, Norms & Structure",
    title: "On the edge",
    gloss: "At the margin, around the outside.",
    hook: "PERIPHERAL things sit at the FRINGE; to SKIRT something is to go around its edge.",
    words: [
      { w: "peripheral", d: "on the outer edge; marginal" },
      { w: "fringe", d: "margin, periphery" },
      { w: "skirt", d: "border; go around; avoid" },
    ],
  },
  {
    id: "offcuff",
    section: "Order, Norms & Structure",
    title: "Off the cuff",
    gloss: "Unplanned, casual, improvised.",
    hook: "An OFFHAND remark is casual; an INADVERTENT one is accidental; a MAKESHIFT fix is thrown together for now.",
    words: [
      { w: "offhand", d: "casual, unprepared" },
      { w: "inadvertent", d: "unintentional, accidental" },
      { w: "makeshift", d: "improvised, temporary" },
    ],
  },
  {
    id: "demand",
    section: "Order, Norms & Structure",
    title: "Hard graft & high standards",
    gloss: "Demanding work and the diligence it takes.",
    hook: "ARDUOUS work under an EXACTING boss demands you be METICULOUS and SEDULOUS — careful and tireless.",
    words: [
      { w: "arduous", d: "very difficult, strenuous" },
      { w: "exacting", d: "severe in its demands" },
      { w: "meticulous", d: "extremely careful about detail" },
      { w: "sedulous", d: "diligent, persevering" },
    ],
  },
  {
    id: "knowhow",
    section: "Order, Norms & Structure",
    title: "Know-how & novices",
    gloss: "Familiarity with a subject — or the lack of it.",
    hook: "Be CONVERSANT and you know your stuff; RUDIMENTARY knowledge is just the basics; a LAYPERSON is no expert at all.",
    words: [
      { w: "conversant", d: "well-versed, familiar with" },
      { w: "rudimentary", d: "basic, elementary" },
      { w: "layperson", d: "a non-expert, non-specialist" },
    ],
  },
  {
    id: "tolerate",
    section: "Order, Norms & Structure",
    title: "Putting up with it",
    gloss: "Allowing or quietly accepting something.",
    hook: "To CONDONE is to overlook a wrong; to COUNTENANCE is to tolerate or approve it.",
    words: [
      { w: "condone", d: "overlook or permit (a wrong)" },
      { w: "countenance", d: "tolerate, approve; also the face" },
    ],
  },

  {
    id: "connect",
    section: "Speech & Expression",
    title: "Joining the dots",
    gloss: "Little linking words that steer an argument.",
    hook: "LIKEWISE and MOREOVER add on; CONVERSELY and WHEREAS flip to the other side; INASMUCH ties cause to effect.",
    words: [
      { w: "likewise", d: "similarly, also, in addition" },
      { w: "moreover", d: "besides, furthermore" },
      { w: "conversely", d: "on the other hand, oppositely" },
      { w: "whereas", d: "while on the contrary" },
      { w: "inasmuch", d: "seeing that; to the extent that" },
    ],
  },

  // ---------------- Loners ----------------
  {
    id: "loners",
    section: "Loners",
    title: "Learn these on their own",
    gloss: "These don't share a meaning-family — give each its own private hook.",
    hook: "No shared theme here. Tie each to a vivid image: a TORRID desert, a map-maker doing CARTOGRAPHY, GOOSEBUMPS rising on your arm.",
    words: [
      { w: "aesthetic", d: "concerning beauty or taste" },
      { w: "artifact", d: "an object made by humans" },
      { w: "cartography", d: "the craft of map-making" },
      { w: "goosebumps", d: "skin bumps from cold or fear" },
      { w: "net", d: "remaining after deductions" },
      { w: "sentient", d: "able to feel and perceive" },
      { w: "torrid", d: "scorching hot; intensely passionate" },
      { w: "hearken", d: "listen, pay heed" },
      { w: "table", d: "set aside for later discussion" },
    ],
  },
];
